name = "stats-server"
main = "index.js"

workers_dev = true
compatibility_date = "2022-02-07"

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "STATSDB"
preview_id = "9bb6a68d2e2546db88579aa3737e85ba"
id = "9bb6a68d2e2546db88579aa3737e85ba"

# [secrets]
# FITBIT_CLIENT_ID
# FITBIT_CLIENT_SECRET